---
version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 35775:5775/udp
      - 36686:16686
    networks: 
      - jaeger-net
networks:
  jaeger-net:
    driver: bridge
