---
version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 33000:3000
    environment:
      #GF_SERVER_ROOT_URL: http://grafana.server.name
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - infosak_default
      - default
networks:
  infosak_default:
    external: true
