---
version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      #GF_SERVER_ROOT_URL: http://grafana.server.name
      GF_SECURITY_ADMIN_PASSWORD: admin
    links:
      - prometheus
  prometheus:
    build: prometheus
    ports:
      - 9090:9090
