global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
# - job_name: 'infosak-cases'
#   static_configs:
#    - targets:
#      - cases-web:5555
# - job_name: 'infosak-identity'
#   static_configs:
#    - targets:
#      - identity-web:5555
